apiVersion: "0.1.0-alpha.1"
kind: Resource
metadata:
  name: example-resource
  namespace: my-app-ns
  path: /path/to/resource
  description: "Another example resource for testing purposes"
spec:
  schema:
    type: object
    properties:
      name:
        type: string
      value:
        type: integer
  value:
    name: example-resource
    value: 42
